name: PHP + Tailwind CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Tailwind CLI
      run: npm install --omit=optional

    - name: Build Tailwind CSS
      run: npx tailwindcss -i ./assets/input.css -o ./assets/output.css

    - name: Check PHP syntax
      run: find . -name "*.php" -exec php -l {} \;
