name: PHP Syntax Check (CI)

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Cek Syntax PHP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Cek Error Syntax PHP
      run: find . -type f -name "*.php" -exec php -l {} \;
